# Site settings
title: Vinícius Temóteo Ferrari - Resume
description: Full-Stack Developer Resume
url: "https://vtferrari.space"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Resume data
resume: site.data.resume

